const baseRedirectURL = "https://wasmegg.netlify.app/artifact-explorer";

const artifactIds = [
  "aurelian-brooch-1",
  "aurelian-brooch-2",
  "aurelian-brooch-3",
  "aurelian-brooch-4",
  "beak-of-midas-1",
  "beak-of-midas-2",
  "beak-of-midas-3",
  "beak-of-midas-4",
  "book-of-basan-1",
  "book-of-basan-2",
  "book-of-basan-3",
  "book-of-basan-4",
  "carved-rainstick-1",
  "carved-rainstick-2",
  "carved-rainstick-3",
  "carved-rainstick-4",
  "demeters-necklace-1",
  "demeters-necklace-2",
  "demeters-necklace-3",
  "demeters-necklace-4",
  "dilithium-monocle-1",
  "dilithium-monocle-2",
  "dilithium-monocle-3",
  "dilithium-monocle-4",
  "gusset-1",
  "gusset-2",
  "gusset-3",
  "gusset-4",
  "interstellar-compass-1",
  "interstellar-compass-2",
  "interstellar-compass-3",
  "interstellar-compass-4",
  "light-of-eggendil-1",
  "light-of-eggendil-2",
  "light-of-eggendil-3",
  "light-of-eggendil-4",
  "lunar-totem-1",
  "lunar-totem-2",
  "lunar-totem-3",
  "lunar-totem-4",
  "mercurys-lens-1",
  "mercurys-lens-2",
  "mercurys-lens-3",
  "mercurys-lens-4",
  "neodymium-medallion-1",
  "neodymium-medallion-2",
  "neodymium-medallion-3",
  "neodymium-medallion-4",
  "phoenix-feather-1",
  "phoenix-feather-2",
  "phoenix-feather-3",
  "phoenix-feather-4",
  "puzzle-cube-1",
  "puzzle-cube-2",
  "puzzle-cube-3",
  "puzzle-cube-4",
  "quantum-metronome-1",
  "quantum-metronome-2",
  "quantum-metronome-3",
  "quantum-metronome-4",
  "ship-in-a-bottle-1",
  "ship-in-a-bottle-2",
  "ship-in-a-bottle-3",
  "ship-in-a-bottle-4",
  "tachyon-deflector-1",
  "tachyon-deflector-2",
  "tachyon-deflector-3",
  "tachyon-deflector-4",
  "the-chalice-1",
  "the-chalice-2",
  "the-chalice-3",
  "the-chalice-4",
  "titanium-actuator-1",
  "titanium-actuator-2",
  "titanium-actuator-3",
  "titanium-actuator-4",
  "tungsten-ankh-1",
  "tungsten-ankh-2",
  "tungsten-ankh-3",
  "tungsten-ankh-4",
  "vial-of-martian-dust-1",
  "vial-of-martian-dust-2",
  "vial-of-martian-dust-3",
  "vial-of-martian-dust-4",
];

const missionIds = [
  "chicken-one-short",
  "chicken-one-standard",
  "chicken-one-extended",
  "chicken-nine-short",
  "chicken-nine-standard",
  "chicken-nine-extended",
  "chicken-heavy-short",
  "chicken-heavy-standard",
  "chicken-heavy-extended",
  "bcr-short",
  "bcr-standard",
  "bcr-extended",
  "quintillion-chicken-short",
  "quintillion-chicken-standard",
  "quintillion-chicken-extended",
  "cornish-hen-corvette-short",
  "cornish-hen-corvette-standard",
  "cornish-hen-corvette-extended",
  "galeggtica-short",
  "galeggtica-standard",
  "galeggtica-extended",
  "defihent-short",
  "defihent-standard",
  "defihent-extended",
  "voyegger-short",
  "voyegger-standard",
  "voyegger-extended",
  "henerprise-short",
  "henerprise-standard",
  "henerprise-extended",
];

async function handleRequest(request) {
  const url = new URL(request.url);
  const code = url.pathname.replace(/^\/(.*?)\/?$/, "$1");
  let redirectURL = baseRedirectURL + "/";
  if (artifactIds.includes(code)) {
    redirectURL = baseRedirectURL + `/#/artifact/${code}`;
  }
  if (missionIds.includes(code)) {
    redirectURL = baseRedirectURL + `/#/mission/${code}`;
  }
  return Response.redirect(redirectURL, 302);
}

addEventListener("fetch", async event => {
  event.respondWith(handleRequest(event.request));
});
