// Code generated by "python3 effect_numbers.py"; DO NOT EDIT.

package artifacts

import "github.com/fanaticscripter/EggContractor/api"

var _effectDeltas = map[item]float64{
	{
		Name:   api.ArtifactSpec_PUZZLE_CUBE,
		Level:  api.ArtifactSpec_INFERIOR,
		Rarity: api.ArtifactSpec_COMMON,
	}: -0.05,
	{
		Name:   api.ArtifactSpec_PUZZLE_CUBE,
		Level:  api.ArtifactSpec_LESSER,
		Rarity: api.ArtifactSpec_COMMON,
	}: -0.1,
	{
		Name:   api.ArtifactSpec_PUZZLE_CUBE,
		Level:  api.ArtifactSpec_LESSER,
		Rarity: api.ArtifactSpec_EPIC,
	}: -0.15,
	{
		Name:   api.ArtifactSpec_PUZZLE_CUBE,
		Level:  api.ArtifactSpec_NORMAL,
		Rarity: api.ArtifactSpec_COMMON,
	}: -0.2,
	{
		Name:   api.ArtifactSpec_PUZZLE_CUBE,
		Level:  api.ArtifactSpec_NORMAL,
		Rarity: api.ArtifactSpec_RARE,
	}: -0.22,
	{
		Name:   api.ArtifactSpec_PUZZLE_CUBE,
		Level:  api.ArtifactSpec_GREATER,
		Rarity: api.ArtifactSpec_COMMON,
	}: -0.5,
	{
		Name:   api.ArtifactSpec_PUZZLE_CUBE,
		Level:  api.ArtifactSpec_GREATER,
		Rarity: api.ArtifactSpec_RARE,
	}: -0.53,
	{
		Name:   api.ArtifactSpec_PUZZLE_CUBE,
		Level:  api.ArtifactSpec_GREATER,
		Rarity: api.ArtifactSpec_EPIC,
	}: -0.55,
	{
		Name:   api.ArtifactSpec_PUZZLE_CUBE,
		Level:  api.ArtifactSpec_GREATER,
		Rarity: api.ArtifactSpec_LEGENDARY,
	}: -0.6,
	{
		Name:   api.ArtifactSpec_LUNAR_TOTEM,
		Level:  api.ArtifactSpec_INFERIOR,
		Rarity: api.ArtifactSpec_COMMON,
	}: 0.5,
	{
		Name:   api.ArtifactSpec_LUNAR_TOTEM,
		Level:  api.ArtifactSpec_LESSER,
		Rarity: api.ArtifactSpec_COMMON,
	}: 1.0,
	{
		Name:   api.ArtifactSpec_LUNAR_TOTEM,
		Level:  api.ArtifactSpec_LESSER,
		Rarity: api.ArtifactSpec_RARE,
	}: 1.5,
	{
		Name:   api.ArtifactSpec_LUNAR_TOTEM,
		Level:  api.ArtifactSpec_NORMAL,
		Rarity: api.ArtifactSpec_COMMON,
	}: 3.0,
	{
		Name:   api.ArtifactSpec_LUNAR_TOTEM,
		Level:  api.ArtifactSpec_NORMAL,
		Rarity: api.ArtifactSpec_RARE,
	}: 4.0,
	{
		Name:   api.ArtifactSpec_LUNAR_TOTEM,
		Level:  api.ArtifactSpec_GREATER,
		Rarity: api.ArtifactSpec_COMMON,
	}: 5.0,
	{
		Name:   api.ArtifactSpec_LUNAR_TOTEM,
		Level:  api.ArtifactSpec_GREATER,
		Rarity: api.ArtifactSpec_RARE,
	}: 7.0,
	{
		Name:   api.ArtifactSpec_LUNAR_TOTEM,
		Level:  api.ArtifactSpec_GREATER,
		Rarity: api.ArtifactSpec_EPIC,
	}: 9.0,
	{
		Name:   api.ArtifactSpec_DEMETERS_NECKLACE,
		Level:  api.ArtifactSpec_INFERIOR,
		Rarity: api.ArtifactSpec_COMMON,
	}: 0.1,
	{
		Name:   api.ArtifactSpec_DEMETERS_NECKLACE,
		Level:  api.ArtifactSpec_LESSER,
		Rarity: api.ArtifactSpec_COMMON,
	}: 0.25,
	{
		Name:   api.ArtifactSpec_DEMETERS_NECKLACE,
		Level:  api.ArtifactSpec_LESSER,
		Rarity: api.ArtifactSpec_RARE,
	}: 0.35000000000000003,
	{
		Name:   api.ArtifactSpec_DEMETERS_NECKLACE,
		Level:  api.ArtifactSpec_NORMAL,
		Rarity: api.ArtifactSpec_COMMON,
	}: 0.5,
	{
		Name:   api.ArtifactSpec_DEMETERS_NECKLACE,
		Level:  api.ArtifactSpec_NORMAL,
		Rarity: api.ArtifactSpec_RARE,
	}: 0.6,
	{
		Name:   api.ArtifactSpec_DEMETERS_NECKLACE,
		Level:  api.ArtifactSpec_NORMAL,
		Rarity: api.ArtifactSpec_EPIC,
	}: 0.75,
	{
		Name:   api.ArtifactSpec_DEMETERS_NECKLACE,
		Level:  api.ArtifactSpec_GREATER,
		Rarity: api.ArtifactSpec_COMMON,
	}: 1.0,
	{
		Name:   api.ArtifactSpec_DEMETERS_NECKLACE,
		Level:  api.ArtifactSpec_GREATER,
		Rarity: api.ArtifactSpec_RARE,
	}: 1.25,
	{
		Name:   api.ArtifactSpec_DEMETERS_NECKLACE,
		Level:  api.ArtifactSpec_GREATER,
		Rarity: api.ArtifactSpec_EPIC,
	}: 1.5,
	{
		Name:   api.ArtifactSpec_DEMETERS_NECKLACE,
		Level:  api.ArtifactSpec_GREATER,
		Rarity: api.ArtifactSpec_LEGENDARY,
	}: 2.0,
	{
		Name:   api.ArtifactSpec_VIAL_MARTIAN_DUST,
		Level:  api.ArtifactSpec_INFERIOR,
		Rarity: api.ArtifactSpec_COMMON,
	}: 10.0,
	{
		Name:   api.ArtifactSpec_VIAL_MARTIAN_DUST,
		Level:  api.ArtifactSpec_LESSER,
		Rarity: api.ArtifactSpec_COMMON,
	}: 50.0,
	{
		Name:   api.ArtifactSpec_VIAL_MARTIAN_DUST,
		Level:  api.ArtifactSpec_LESSER,
		Rarity: api.ArtifactSpec_RARE,
	}: 60.0,
	{
		Name:   api.ArtifactSpec_VIAL_MARTIAN_DUST,
		Level:  api.ArtifactSpec_NORMAL,
		Rarity: api.ArtifactSpec_COMMON,
	}: 100.0,
	{
		Name:   api.ArtifactSpec_VIAL_MARTIAN_DUST,
		Level:  api.ArtifactSpec_NORMAL,
		Rarity: api.ArtifactSpec_EPIC,
	}: 150.0,
	{
		Name:   api.ArtifactSpec_VIAL_MARTIAN_DUST,
		Level:  api.ArtifactSpec_GREATER,
		Rarity: api.ArtifactSpec_COMMON,
	}: 200.0,
	{
		Name:   api.ArtifactSpec_VIAL_MARTIAN_DUST,
		Level:  api.ArtifactSpec_GREATER,
		Rarity: api.ArtifactSpec_RARE,
	}: 300.0,
	{
		Name:   api.ArtifactSpec_VIAL_MARTIAN_DUST,
		Level:  api.ArtifactSpec_GREATER,
		Rarity: api.ArtifactSpec_LEGENDARY,
	}: 500.0,
	{
		Name:   api.ArtifactSpec_AURELIAN_BROOCH,
		Level:  api.ArtifactSpec_INFERIOR,
		Rarity: api.ArtifactSpec_COMMON,
	}: 0.1,
	{
		Name:   api.ArtifactSpec_AURELIAN_BROOCH,
		Level:  api.ArtifactSpec_LESSER,
		Rarity: api.ArtifactSpec_COMMON,
	}: 0.25,
	{
		Name:   api.ArtifactSpec_AURELIAN_BROOCH,
		Level:  api.ArtifactSpec_NORMAL,
		Rarity: api.ArtifactSpec_COMMON,
	}: 0.5,
	{
		Name:   api.ArtifactSpec_AURELIAN_BROOCH,
		Level:  api.ArtifactSpec_NORMAL,
		Rarity: api.ArtifactSpec_RARE,
	}: 0.6,
	{
		Name:   api.ArtifactSpec_AURELIAN_BROOCH,
		Level:  api.ArtifactSpec_NORMAL,
		Rarity: api.ArtifactSpec_EPIC,
	}: 0.7000000000000001,
	{
		Name:   api.ArtifactSpec_AURELIAN_BROOCH,
		Level:  api.ArtifactSpec_GREATER,
		Rarity: api.ArtifactSpec_COMMON,
	}: 1.0,
	{
		Name:   api.ArtifactSpec_AURELIAN_BROOCH,
		Level:  api.ArtifactSpec_GREATER,
		Rarity: api.ArtifactSpec_RARE,
	}: 1.25,
	{
		Name:   api.ArtifactSpec_AURELIAN_BROOCH,
		Level:  api.ArtifactSpec_GREATER,
		Rarity: api.ArtifactSpec_EPIC,
	}: 1.5,
	{
		Name:   api.ArtifactSpec_AURELIAN_BROOCH,
		Level:  api.ArtifactSpec_GREATER,
		Rarity: api.ArtifactSpec_LEGENDARY,
	}: 2.0,
	{
		Name:   api.ArtifactSpec_TUNGSTEN_ANKH,
		Level:  api.ArtifactSpec_INFERIOR,
		Rarity: api.ArtifactSpec_COMMON,
	}: 0.1,
	{
		Name:   api.ArtifactSpec_TUNGSTEN_ANKH,
		Level:  api.ArtifactSpec_LESSER,
		Rarity: api.ArtifactSpec_COMMON,
	}: 0.25,
	{
		Name:   api.ArtifactSpec_TUNGSTEN_ANKH,
		Level:  api.ArtifactSpec_LESSER,
		Rarity: api.ArtifactSpec_RARE,
	}: 0.28,
	{
		Name:   api.ArtifactSpec_TUNGSTEN_ANKH,
		Level:  api.ArtifactSpec_NORMAL,
		Rarity: api.ArtifactSpec_COMMON,
	}: 0.5,
	{
		Name:   api.ArtifactSpec_TUNGSTEN_ANKH,
		Level:  api.ArtifactSpec_NORMAL,
		Rarity: api.ArtifactSpec_RARE,
	}: 0.75,
	{
		Name:   api.ArtifactSpec_TUNGSTEN_ANKH,
		Level:  api.ArtifactSpec_NORMAL,
		Rarity: api.ArtifactSpec_LEGENDARY,
	}: 1.0,
	{
		Name:   api.ArtifactSpec_TUNGSTEN_ANKH,
		Level:  api.ArtifactSpec_GREATER,
		Rarity: api.ArtifactSpec_COMMON,
	}: 1.0,
	{
		Name:   api.ArtifactSpec_TUNGSTEN_ANKH,
		Level:  api.ArtifactSpec_GREATER,
		Rarity: api.ArtifactSpec_RARE,
	}: 1.25,
	{
		Name:   api.ArtifactSpec_TUNGSTEN_ANKH,
		Level:  api.ArtifactSpec_GREATER,
		Rarity: api.ArtifactSpec_LEGENDARY,
	}: 1.5,
	{
		Name:   api.ArtifactSpec_ORNATE_GUSSET,
		Level:  api.ArtifactSpec_INFERIOR,
		Rarity: api.ArtifactSpec_COMMON,
	}: 0.05,
	{
		Name:   api.ArtifactSpec_ORNATE_GUSSET,
		Level:  api.ArtifactSpec_LESSER,
		Rarity: api.ArtifactSpec_COMMON,
	}: 0.1,
	{
		Name:   api.ArtifactSpec_ORNATE_GUSSET,
		Level:  api.ArtifactSpec_LESSER,
		Rarity: api.ArtifactSpec_EPIC,
	}: 0.12,
	{
		Name:   api.ArtifactSpec_ORNATE_GUSSET,
		Level:  api.ArtifactSpec_NORMAL,
		Rarity: api.ArtifactSpec_COMMON,
	}: 0.15,
	{
		Name:   api.ArtifactSpec_ORNATE_GUSSET,
		Level:  api.ArtifactSpec_NORMAL,
		Rarity: api.ArtifactSpec_RARE,
	}: 0.16,
	{
		Name:   api.ArtifactSpec_ORNATE_GUSSET,
		Level:  api.ArtifactSpec_GREATER,
		Rarity: api.ArtifactSpec_COMMON,
	}: 0.2,
	{
		Name:   api.ArtifactSpec_ORNATE_GUSSET,
		Level:  api.ArtifactSpec_GREATER,
		Rarity: api.ArtifactSpec_EPIC,
	}: 0.22,
	{
		Name:   api.ArtifactSpec_ORNATE_GUSSET,
		Level:  api.ArtifactSpec_GREATER,
		Rarity: api.ArtifactSpec_LEGENDARY,
	}: 0.25,
	{
		Name:   api.ArtifactSpec_NEODYMIUM_MEDALLION,
		Level:  api.ArtifactSpec_INFERIOR,
		Rarity: api.ArtifactSpec_COMMON,
	}: 0.1,
	{
		Name:   api.ArtifactSpec_NEODYMIUM_MEDALLION,
		Level:  api.ArtifactSpec_LESSER,
		Rarity: api.ArtifactSpec_COMMON,
	}: 0.25,
	{
		Name:   api.ArtifactSpec_NEODYMIUM_MEDALLION,
		Level:  api.ArtifactSpec_LESSER,
		Rarity: api.ArtifactSpec_RARE,
	}: 0.3,
	{
		Name:   api.ArtifactSpec_NEODYMIUM_MEDALLION,
		Level:  api.ArtifactSpec_NORMAL,
		Rarity: api.ArtifactSpec_COMMON,
	}: 0.5,
	{
		Name:   api.ArtifactSpec_NEODYMIUM_MEDALLION,
		Level:  api.ArtifactSpec_NORMAL,
		Rarity: api.ArtifactSpec_EPIC,
	}: 0.6,
	{
		Name:   api.ArtifactSpec_NEODYMIUM_MEDALLION,
		Level:  api.ArtifactSpec_GREATER,
		Rarity: api.ArtifactSpec_COMMON,
	}: 1.0,
	{
		Name:   api.ArtifactSpec_NEODYMIUM_MEDALLION,
		Level:  api.ArtifactSpec_GREATER,
		Rarity: api.ArtifactSpec_RARE,
	}: 1.1,
	{
		Name:   api.ArtifactSpec_NEODYMIUM_MEDALLION,
		Level:  api.ArtifactSpec_GREATER,
		Rarity: api.ArtifactSpec_EPIC,
	}: 1.2,
	{
		Name:   api.ArtifactSpec_NEODYMIUM_MEDALLION,
		Level:  api.ArtifactSpec_GREATER,
		Rarity: api.ArtifactSpec_LEGENDARY,
	}: 1.3,
	{
		Name:   api.ArtifactSpec_MERCURYS_LENS,
		Level:  api.ArtifactSpec_INFERIOR,
		Rarity: api.ArtifactSpec_COMMON,
	}: 0.1,
	{
		Name:   api.ArtifactSpec_MERCURYS_LENS,
		Level:  api.ArtifactSpec_LESSER,
		Rarity: api.ArtifactSpec_COMMON,
	}: 0.2,
	{
		Name:   api.ArtifactSpec_MERCURYS_LENS,
		Level:  api.ArtifactSpec_LESSER,
		Rarity: api.ArtifactSpec_RARE,
	}: 0.22,
	{
		Name:   api.ArtifactSpec_MERCURYS_LENS,
		Level:  api.ArtifactSpec_NORMAL,
		Rarity: api.ArtifactSpec_COMMON,
	}: 0.5,
	{
		Name:   api.ArtifactSpec_MERCURYS_LENS,
		Level:  api.ArtifactSpec_NORMAL,
		Rarity: api.ArtifactSpec_RARE,
	}: 0.55,
	{
		Name:   api.ArtifactSpec_MERCURYS_LENS,
		Level:  api.ArtifactSpec_GREATER,
		Rarity: api.ArtifactSpec_COMMON,
	}: 1.0,
	{
		Name:   api.ArtifactSpec_MERCURYS_LENS,
		Level:  api.ArtifactSpec_GREATER,
		Rarity: api.ArtifactSpec_RARE,
	}: 1.25,
	{
		Name:   api.ArtifactSpec_MERCURYS_LENS,
		Level:  api.ArtifactSpec_GREATER,
		Rarity: api.ArtifactSpec_EPIC,
	}: 1.5,
	{
		Name:   api.ArtifactSpec_MERCURYS_LENS,
		Level:  api.ArtifactSpec_GREATER,
		Rarity: api.ArtifactSpec_LEGENDARY,
	}: 2.0,
	{
		Name:   api.ArtifactSpec_BEAK_OF_MIDAS,
		Level:  api.ArtifactSpec_INFERIOR,
		Rarity: api.ArtifactSpec_COMMON,
	}: 0.2,
	{
		Name:   api.ArtifactSpec_BEAK_OF_MIDAS,
		Level:  api.ArtifactSpec_LESSER,
		Rarity: api.ArtifactSpec_COMMON,
	}: 0.5,
	{
		Name:   api.ArtifactSpec_BEAK_OF_MIDAS,
		Level:  api.ArtifactSpec_NORMAL,
		Rarity: api.ArtifactSpec_COMMON,
	}: 1.0,
	{
		Name:   api.ArtifactSpec_BEAK_OF_MIDAS,
		Level:  api.ArtifactSpec_NORMAL,
		Rarity: api.ArtifactSpec_RARE,
	}: 2.0,
	{
		Name:   api.ArtifactSpec_BEAK_OF_MIDAS,
		Level:  api.ArtifactSpec_GREATER,
		Rarity: api.ArtifactSpec_COMMON,
	}: 5.0,
	{
		Name:   api.ArtifactSpec_BEAK_OF_MIDAS,
		Level:  api.ArtifactSpec_GREATER,
		Rarity: api.ArtifactSpec_RARE,
	}: 10.0,
	{
		Name:   api.ArtifactSpec_BEAK_OF_MIDAS,
		Level:  api.ArtifactSpec_GREATER,
		Rarity: api.ArtifactSpec_LEGENDARY,
	}: 0,
	{
		Name:   api.ArtifactSpec_CARVED_RAINSTICK,
		Level:  api.ArtifactSpec_INFERIOR,
		Rarity: api.ArtifactSpec_COMMON,
	}: 0.2,
	{
		Name:   api.ArtifactSpec_CARVED_RAINSTICK,
		Level:  api.ArtifactSpec_LESSER,
		Rarity: api.ArtifactSpec_COMMON,
	}: 0.5,
	{
		Name:   api.ArtifactSpec_CARVED_RAINSTICK,
		Level:  api.ArtifactSpec_NORMAL,
		Rarity: api.ArtifactSpec_COMMON,
	}: 1.0,
	{
		Name:   api.ArtifactSpec_CARVED_RAINSTICK,
		Level:  api.ArtifactSpec_GREATER,
		Rarity: api.ArtifactSpec_COMMON,
	}: 4.0,
	{
		Name:   api.ArtifactSpec_CARVED_RAINSTICK,
		Level:  api.ArtifactSpec_GREATER,
		Rarity: api.ArtifactSpec_EPIC,
	}: 9.0,
	{
		Name:   api.ArtifactSpec_CARVED_RAINSTICK,
		Level:  api.ArtifactSpec_GREATER,
		Rarity: api.ArtifactSpec_LEGENDARY,
	}: 0,
	{
		Name:   api.ArtifactSpec_INTERSTELLAR_COMPASS,
		Level:  api.ArtifactSpec_INFERIOR,
		Rarity: api.ArtifactSpec_COMMON,
	}: 0.05,
	{
		Name:   api.ArtifactSpec_INTERSTELLAR_COMPASS,
		Level:  api.ArtifactSpec_LESSER,
		Rarity: api.ArtifactSpec_COMMON,
	}: 0.1,
	{
		Name:   api.ArtifactSpec_INTERSTELLAR_COMPASS,
		Level:  api.ArtifactSpec_NORMAL,
		Rarity: api.ArtifactSpec_COMMON,
	}: 0.2,
	{
		Name:   api.ArtifactSpec_INTERSTELLAR_COMPASS,
		Level:  api.ArtifactSpec_NORMAL,
		Rarity: api.ArtifactSpec_RARE,
	}: 0.22,
	{
		Name:   api.ArtifactSpec_INTERSTELLAR_COMPASS,
		Level:  api.ArtifactSpec_GREATER,
		Rarity: api.ArtifactSpec_COMMON,
	}: 0.3,
	{
		Name:   api.ArtifactSpec_INTERSTELLAR_COMPASS,
		Level:  api.ArtifactSpec_GREATER,
		Rarity: api.ArtifactSpec_RARE,
	}: 0.35000000000000003,
	{
		Name:   api.ArtifactSpec_INTERSTELLAR_COMPASS,
		Level:  api.ArtifactSpec_GREATER,
		Rarity: api.ArtifactSpec_EPIC,
	}: 0.4,
	{
		Name:   api.ArtifactSpec_INTERSTELLAR_COMPASS,
		Level:  api.ArtifactSpec_GREATER,
		Rarity: api.ArtifactSpec_LEGENDARY,
	}: 0.5,
	{
		Name:   api.ArtifactSpec_THE_CHALICE,
		Level:  api.ArtifactSpec_INFERIOR,
		Rarity: api.ArtifactSpec_COMMON,
	}: 0.05,
	{
		Name:   api.ArtifactSpec_THE_CHALICE,
		Level:  api.ArtifactSpec_LESSER,
		Rarity: api.ArtifactSpec_COMMON,
	}: 0.1,
	{
		Name:   api.ArtifactSpec_THE_CHALICE,
		Level:  api.ArtifactSpec_LESSER,
		Rarity: api.ArtifactSpec_EPIC,
	}: 0.15,
	{
		Name:   api.ArtifactSpec_THE_CHALICE,
		Level:  api.ArtifactSpec_NORMAL,
		Rarity: api.ArtifactSpec_COMMON,
	}: 0.2,
	{
		Name:   api.ArtifactSpec_THE_CHALICE,
		Level:  api.ArtifactSpec_NORMAL,
		Rarity: api.ArtifactSpec_RARE,
	}: 0.23,
	{
		Name:   api.ArtifactSpec_THE_CHALICE,
		Level:  api.ArtifactSpec_NORMAL,
		Rarity: api.ArtifactSpec_EPIC,
	}: 0.25,
	{
		Name:   api.ArtifactSpec_THE_CHALICE,
		Level:  api.ArtifactSpec_GREATER,
		Rarity: api.ArtifactSpec_COMMON,
	}: 0.3,
	{
		Name:   api.ArtifactSpec_THE_CHALICE,
		Level:  api.ArtifactSpec_GREATER,
		Rarity: api.ArtifactSpec_EPIC,
	}: 0.35000000000000003,
	{
		Name:   api.ArtifactSpec_THE_CHALICE,
		Level:  api.ArtifactSpec_GREATER,
		Rarity: api.ArtifactSpec_LEGENDARY,
	}: 0.4,
	{
		Name:   api.ArtifactSpec_PHOENIX_FEATHER,
		Level:  api.ArtifactSpec_INFERIOR,
		Rarity: api.ArtifactSpec_COMMON,
	}: 0.25,
	{
		Name:   api.ArtifactSpec_PHOENIX_FEATHER,
		Level:  api.ArtifactSpec_LESSER,
		Rarity: api.ArtifactSpec_COMMON,
	}: 1.0,
	{
		Name:   api.ArtifactSpec_PHOENIX_FEATHER,
		Level:  api.ArtifactSpec_NORMAL,
		Rarity: api.ArtifactSpec_COMMON,
	}: 4.0,
	{
		Name:   api.ArtifactSpec_PHOENIX_FEATHER,
		Level:  api.ArtifactSpec_NORMAL,
		Rarity: api.ArtifactSpec_RARE,
	}: 5.0,
	{
		Name:   api.ArtifactSpec_PHOENIX_FEATHER,
		Level:  api.ArtifactSpec_GREATER,
		Rarity: api.ArtifactSpec_COMMON,
	}: 9.0,
	{
		Name:   api.ArtifactSpec_PHOENIX_FEATHER,
		Level:  api.ArtifactSpec_GREATER,
		Rarity: api.ArtifactSpec_RARE,
	}: 11.0,
	{
		Name:   api.ArtifactSpec_PHOENIX_FEATHER,
		Level:  api.ArtifactSpec_GREATER,
		Rarity: api.ArtifactSpec_LEGENDARY,
	}: 14.0,
	{
		Name:   api.ArtifactSpec_QUANTUM_METRONOME,
		Level:  api.ArtifactSpec_INFERIOR,
		Rarity: api.ArtifactSpec_COMMON,
	}: 0.05,
	{
		Name:   api.ArtifactSpec_QUANTUM_METRONOME,
		Level:  api.ArtifactSpec_LESSER,
		Rarity: api.ArtifactSpec_COMMON,
	}: 0.1,
	{
		Name:   api.ArtifactSpec_QUANTUM_METRONOME,
		Level:  api.ArtifactSpec_LESSER,
		Rarity: api.ArtifactSpec_RARE,
	}: 0.12,
	{
		Name:   api.ArtifactSpec_QUANTUM_METRONOME,
		Level:  api.ArtifactSpec_NORMAL,
		Rarity: api.ArtifactSpec_COMMON,
	}: 0.15,
	{
		Name:   api.ArtifactSpec_QUANTUM_METRONOME,
		Level:  api.ArtifactSpec_NORMAL,
		Rarity: api.ArtifactSpec_RARE,
	}: 0.17,
	{
		Name:   api.ArtifactSpec_QUANTUM_METRONOME,
		Level:  api.ArtifactSpec_NORMAL,
		Rarity: api.ArtifactSpec_EPIC,
	}: 0.2,
	{
		Name:   api.ArtifactSpec_QUANTUM_METRONOME,
		Level:  api.ArtifactSpec_GREATER,
		Rarity: api.ArtifactSpec_COMMON,
	}: 0.25,
	{
		Name:   api.ArtifactSpec_QUANTUM_METRONOME,
		Level:  api.ArtifactSpec_GREATER,
		Rarity: api.ArtifactSpec_RARE,
	}: 0.27,
	{
		Name:   api.ArtifactSpec_QUANTUM_METRONOME,
		Level:  api.ArtifactSpec_GREATER,
		Rarity: api.ArtifactSpec_EPIC,
	}: 0.3,
	{
		Name:   api.ArtifactSpec_QUANTUM_METRONOME,
		Level:  api.ArtifactSpec_GREATER,
		Rarity: api.ArtifactSpec_LEGENDARY,
	}: 0.35000000000000003,
	{
		Name:   api.ArtifactSpec_DILITHIUM_MONOCLE,
		Level:  api.ArtifactSpec_INFERIOR,
		Rarity: api.ArtifactSpec_COMMON,
	}: 0.05,
	{
		Name:   api.ArtifactSpec_DILITHIUM_MONOCLE,
		Level:  api.ArtifactSpec_LESSER,
		Rarity: api.ArtifactSpec_COMMON,
	}: 0.1,
	{
		Name:   api.ArtifactSpec_DILITHIUM_MONOCLE,
		Level:  api.ArtifactSpec_NORMAL,
		Rarity: api.ArtifactSpec_COMMON,
	}: 0.15,
	{
		Name:   api.ArtifactSpec_DILITHIUM_MONOCLE,
		Level:  api.ArtifactSpec_GREATER,
		Rarity: api.ArtifactSpec_COMMON,
	}: 0.2,
	{
		Name:   api.ArtifactSpec_DILITHIUM_MONOCLE,
		Level:  api.ArtifactSpec_GREATER,
		Rarity: api.ArtifactSpec_EPIC,
	}: 0.25,
	{
		Name:   api.ArtifactSpec_DILITHIUM_MONOCLE,
		Level:  api.ArtifactSpec_GREATER,
		Rarity: api.ArtifactSpec_LEGENDARY,
	}: 0.3,
	{
		Name:   api.ArtifactSpec_TITANIUM_ACTUATOR,
		Level:  api.ArtifactSpec_INFERIOR,
		Rarity: api.ArtifactSpec_COMMON,
	}: 1.0,
	{
		Name:   api.ArtifactSpec_TITANIUM_ACTUATOR,
		Level:  api.ArtifactSpec_LESSER,
		Rarity: api.ArtifactSpec_COMMON,
	}: 4.0,
	{
		Name:   api.ArtifactSpec_TITANIUM_ACTUATOR,
		Level:  api.ArtifactSpec_NORMAL,
		Rarity: api.ArtifactSpec_COMMON,
	}: 6.0,
	{
		Name:   api.ArtifactSpec_TITANIUM_ACTUATOR,
		Level:  api.ArtifactSpec_NORMAL,
		Rarity: api.ArtifactSpec_RARE,
	}: 7.0,
	{
		Name:   api.ArtifactSpec_TITANIUM_ACTUATOR,
		Level:  api.ArtifactSpec_GREATER,
		Rarity: api.ArtifactSpec_COMMON,
	}: 10.0,
	{
		Name:   api.ArtifactSpec_TITANIUM_ACTUATOR,
		Level:  api.ArtifactSpec_GREATER,
		Rarity: api.ArtifactSpec_EPIC,
	}: 12.0,
	{
		Name:   api.ArtifactSpec_TITANIUM_ACTUATOR,
		Level:  api.ArtifactSpec_GREATER,
		Rarity: api.ArtifactSpec_LEGENDARY,
	}: 15.0,
	{
		Name:   api.ArtifactSpec_SHIP_IN_A_BOTTLE,
		Level:  api.ArtifactSpec_INFERIOR,
		Rarity: api.ArtifactSpec_COMMON,
	}: 0.2,
	{
		Name:   api.ArtifactSpec_SHIP_IN_A_BOTTLE,
		Level:  api.ArtifactSpec_LESSER,
		Rarity: api.ArtifactSpec_COMMON,
	}: 0.3,
	{
		Name:   api.ArtifactSpec_SHIP_IN_A_BOTTLE,
		Level:  api.ArtifactSpec_NORMAL,
		Rarity: api.ArtifactSpec_COMMON,
	}: 0.5,
	{
		Name:   api.ArtifactSpec_SHIP_IN_A_BOTTLE,
		Level:  api.ArtifactSpec_NORMAL,
		Rarity: api.ArtifactSpec_RARE,
	}: 0.6,
	{
		Name:   api.ArtifactSpec_SHIP_IN_A_BOTTLE,
		Level:  api.ArtifactSpec_GREATER,
		Rarity: api.ArtifactSpec_COMMON,
	}: 0.7000000000000001,
	{
		Name:   api.ArtifactSpec_SHIP_IN_A_BOTTLE,
		Level:  api.ArtifactSpec_GREATER,
		Rarity: api.ArtifactSpec_RARE,
	}: 0.8,
	{
		Name:   api.ArtifactSpec_SHIP_IN_A_BOTTLE,
		Level:  api.ArtifactSpec_GREATER,
		Rarity: api.ArtifactSpec_EPIC,
	}: 0.9,
	{
		Name:   api.ArtifactSpec_SHIP_IN_A_BOTTLE,
		Level:  api.ArtifactSpec_GREATER,
		Rarity: api.ArtifactSpec_LEGENDARY,
	}: 1.0,
	{
		Name:   api.ArtifactSpec_TACHYON_DEFLECTOR,
		Level:  api.ArtifactSpec_INFERIOR,
		Rarity: api.ArtifactSpec_COMMON,
	}: 0.05,
	{
		Name:   api.ArtifactSpec_TACHYON_DEFLECTOR,
		Level:  api.ArtifactSpec_LESSER,
		Rarity: api.ArtifactSpec_COMMON,
	}: 0.08,
	{
		Name:   api.ArtifactSpec_TACHYON_DEFLECTOR,
		Level:  api.ArtifactSpec_NORMAL,
		Rarity: api.ArtifactSpec_COMMON,
	}: 0.12,
	{
		Name:   api.ArtifactSpec_TACHYON_DEFLECTOR,
		Level:  api.ArtifactSpec_NORMAL,
		Rarity: api.ArtifactSpec_RARE,
	}: 0.13,
	{
		Name:   api.ArtifactSpec_TACHYON_DEFLECTOR,
		Level:  api.ArtifactSpec_GREATER,
		Rarity: api.ArtifactSpec_COMMON,
	}: 0.15,
	{
		Name:   api.ArtifactSpec_TACHYON_DEFLECTOR,
		Level:  api.ArtifactSpec_GREATER,
		Rarity: api.ArtifactSpec_RARE,
	}: 0.17,
	{
		Name:   api.ArtifactSpec_TACHYON_DEFLECTOR,
		Level:  api.ArtifactSpec_GREATER,
		Rarity: api.ArtifactSpec_EPIC,
	}: 0.19,
	{
		Name:   api.ArtifactSpec_TACHYON_DEFLECTOR,
		Level:  api.ArtifactSpec_GREATER,
		Rarity: api.ArtifactSpec_LEGENDARY,
	}: 0.2,
	{
		Name:   api.ArtifactSpec_BOOK_OF_BASAN,
		Level:  api.ArtifactSpec_INFERIOR,
		Rarity: api.ArtifactSpec_COMMON,
	}: 0.0025,
	{
		Name:   api.ArtifactSpec_BOOK_OF_BASAN,
		Level:  api.ArtifactSpec_LESSER,
		Rarity: api.ArtifactSpec_COMMON,
	}: 0.005,
	{
		Name:   api.ArtifactSpec_BOOK_OF_BASAN,
		Level:  api.ArtifactSpec_NORMAL,
		Rarity: api.ArtifactSpec_COMMON,
	}: 0.0075,
	{
		Name:   api.ArtifactSpec_BOOK_OF_BASAN,
		Level:  api.ArtifactSpec_NORMAL,
		Rarity: api.ArtifactSpec_EPIC,
	}: 0.008,
	{
		Name:   api.ArtifactSpec_BOOK_OF_BASAN,
		Level:  api.ArtifactSpec_GREATER,
		Rarity: api.ArtifactSpec_COMMON,
	}: 0.01,
	{
		Name:   api.ArtifactSpec_BOOK_OF_BASAN,
		Level:  api.ArtifactSpec_GREATER,
		Rarity: api.ArtifactSpec_EPIC,
	}: 0.011000000000000001,
	{
		Name:   api.ArtifactSpec_BOOK_OF_BASAN,
		Level:  api.ArtifactSpec_GREATER,
		Rarity: api.ArtifactSpec_LEGENDARY,
	}: 0.012,
	{
		Name:   api.ArtifactSpec_LIGHT_OF_EGGENDIL,
		Level:  api.ArtifactSpec_INFERIOR,
		Rarity: api.ArtifactSpec_COMMON,
	}: 0.5,
	{
		Name:   api.ArtifactSpec_LIGHT_OF_EGGENDIL,
		Level:  api.ArtifactSpec_LESSER,
		Rarity: api.ArtifactSpec_COMMON,
	}: 1.0,
	{
		Name:   api.ArtifactSpec_LIGHT_OF_EGGENDIL,
		Level:  api.ArtifactSpec_LESSER,
		Rarity: api.ArtifactSpec_RARE,
	}: 1.2,
	{
		Name:   api.ArtifactSpec_LIGHT_OF_EGGENDIL,
		Level:  api.ArtifactSpec_NORMAL,
		Rarity: api.ArtifactSpec_COMMON,
	}: 9.0,
	{
		Name:   api.ArtifactSpec_LIGHT_OF_EGGENDIL,
		Level:  api.ArtifactSpec_NORMAL,
		Rarity: api.ArtifactSpec_RARE,
	}: 14.0,
	{
		Name:   api.ArtifactSpec_LIGHT_OF_EGGENDIL,
		Level:  api.ArtifactSpec_GREATER,
		Rarity: api.ArtifactSpec_COMMON,
	}: 99.0,
	{
		Name:   api.ArtifactSpec_LIGHT_OF_EGGENDIL,
		Level:  api.ArtifactSpec_GREATER,
		Rarity: api.ArtifactSpec_EPIC,
	}: 149.0,
	{
		Name:   api.ArtifactSpec_LIGHT_OF_EGGENDIL,
		Level:  api.ArtifactSpec_GREATER,
		Rarity: api.ArtifactSpec_LEGENDARY,
	}: 249.0,
	{
		Name:   api.ArtifactSpec_LUNAR_STONE,
		Level:  api.ArtifactSpec_INFERIOR,
		Rarity: api.ArtifactSpec_COMMON,
	}: 0.2,
	{
		Name:   api.ArtifactSpec_LUNAR_STONE,
		Level:  api.ArtifactSpec_LESSER,
		Rarity: api.ArtifactSpec_COMMON,
	}: 0.3,
	{
		Name:   api.ArtifactSpec_LUNAR_STONE,
		Level:  api.ArtifactSpec_NORMAL,
		Rarity: api.ArtifactSpec_COMMON,
	}: 0.4,
	{
		Name:   api.ArtifactSpec_SHELL_STONE,
		Level:  api.ArtifactSpec_INFERIOR,
		Rarity: api.ArtifactSpec_COMMON,
	}: 0.05,
	{
		Name:   api.ArtifactSpec_SHELL_STONE,
		Level:  api.ArtifactSpec_LESSER,
		Rarity: api.ArtifactSpec_COMMON,
	}: 0.08,
	{
		Name:   api.ArtifactSpec_SHELL_STONE,
		Level:  api.ArtifactSpec_NORMAL,
		Rarity: api.ArtifactSpec_COMMON,
	}: 0.1,
	{
		Name:   api.ArtifactSpec_TACHYON_STONE,
		Level:  api.ArtifactSpec_INFERIOR,
		Rarity: api.ArtifactSpec_COMMON,
	}: 0.02,
	{
		Name:   api.ArtifactSpec_TACHYON_STONE,
		Level:  api.ArtifactSpec_LESSER,
		Rarity: api.ArtifactSpec_COMMON,
	}: 0.04,
	{
		Name:   api.ArtifactSpec_TACHYON_STONE,
		Level:  api.ArtifactSpec_NORMAL,
		Rarity: api.ArtifactSpec_COMMON,
	}: 0.05,
	{
		Name:   api.ArtifactSpec_TERRA_STONE,
		Level:  api.ArtifactSpec_INFERIOR,
		Rarity: api.ArtifactSpec_COMMON,
	}: 10.0,
	{
		Name:   api.ArtifactSpec_TERRA_STONE,
		Level:  api.ArtifactSpec_LESSER,
		Rarity: api.ArtifactSpec_COMMON,
	}: 50.0,
	{
		Name:   api.ArtifactSpec_TERRA_STONE,
		Level:  api.ArtifactSpec_NORMAL,
		Rarity: api.ArtifactSpec_COMMON,
	}: 100.0,
	{
		Name:   api.ArtifactSpec_SOUL_STONE,
		Level:  api.ArtifactSpec_INFERIOR,
		Rarity: api.ArtifactSpec_COMMON,
	}: 0.05,
	{
		Name:   api.ArtifactSpec_SOUL_STONE,
		Level:  api.ArtifactSpec_LESSER,
		Rarity: api.ArtifactSpec_COMMON,
	}: 0.1,
	{
		Name:   api.ArtifactSpec_SOUL_STONE,
		Level:  api.ArtifactSpec_NORMAL,
		Rarity: api.ArtifactSpec_COMMON,
	}: 0.25,
	{
		Name:   api.ArtifactSpec_DILITHIUM_STONE,
		Level:  api.ArtifactSpec_INFERIOR,
		Rarity: api.ArtifactSpec_COMMON,
	}: 0.03,
	{
		Name:   api.ArtifactSpec_DILITHIUM_STONE,
		Level:  api.ArtifactSpec_LESSER,
		Rarity: api.ArtifactSpec_COMMON,
	}: 0.06,
	{
		Name:   api.ArtifactSpec_DILITHIUM_STONE,
		Level:  api.ArtifactSpec_NORMAL,
		Rarity: api.ArtifactSpec_COMMON,
	}: 0.08,
	{
		Name:   api.ArtifactSpec_QUANTUM_STONE,
		Level:  api.ArtifactSpec_INFERIOR,
		Rarity: api.ArtifactSpec_COMMON,
	}: 0.02,
	{
		Name:   api.ArtifactSpec_QUANTUM_STONE,
		Level:  api.ArtifactSpec_LESSER,
		Rarity: api.ArtifactSpec_COMMON,
	}: 0.04,
	{
		Name:   api.ArtifactSpec_QUANTUM_STONE,
		Level:  api.ArtifactSpec_NORMAL,
		Rarity: api.ArtifactSpec_COMMON,
	}: 0.05,
	{
		Name:   api.ArtifactSpec_LIFE_STONE,
		Level:  api.ArtifactSpec_INFERIOR,
		Rarity: api.ArtifactSpec_COMMON,
	}: 0.02,
	{
		Name:   api.ArtifactSpec_LIFE_STONE,
		Level:  api.ArtifactSpec_LESSER,
		Rarity: api.ArtifactSpec_COMMON,
	}: 0.03,
	{
		Name:   api.ArtifactSpec_LIFE_STONE,
		Level:  api.ArtifactSpec_NORMAL,
		Rarity: api.ArtifactSpec_COMMON,
	}: 0.04,
	{
		Name:   api.ArtifactSpec_CLARITY_STONE,
		Level:  api.ArtifactSpec_INFERIOR,
		Rarity: api.ArtifactSpec_COMMON,
	}: 0.25,
	{
		Name:   api.ArtifactSpec_CLARITY_STONE,
		Level:  api.ArtifactSpec_LESSER,
		Rarity: api.ArtifactSpec_COMMON,
	}: 0.5,
	{
		Name:   api.ArtifactSpec_CLARITY_STONE,
		Level:  api.ArtifactSpec_NORMAL,
		Rarity: api.ArtifactSpec_COMMON,
	}: 1.0,
	{
		Name:   api.ArtifactSpec_PROPHECY_STONE,
		Level:  api.ArtifactSpec_INFERIOR,
		Rarity: api.ArtifactSpec_COMMON,
	}: 0.0005,
	{
		Name:   api.ArtifactSpec_PROPHECY_STONE,
		Level:  api.ArtifactSpec_LESSER,
		Rarity: api.ArtifactSpec_COMMON,
	}: 0.001,
	{
		Name:   api.ArtifactSpec_PROPHECY_STONE,
		Level:  api.ArtifactSpec_NORMAL,
		Rarity: api.ArtifactSpec_COMMON,
	}: 0.0015,
}
